import type React from "react";

export const styles = {
  backdrop: {
    position: "fixed" as const,
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "color-mix(in srgb, var(--bg-primary) 60%, transparent)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 1000,
    animation: "skills-backdrop-in 0.15s ease-out",
  } as React.CSSProperties,
  modal: {
    width: "calc(100vw - 250px - var(--right-panel-width, 250px) - 10px)",
    maxWidth: "800px",
    maxHeight: "calc(100vh - 24px - 10px)",
    backgroundColor: "var(--bg-primary)",
    borderRadius: "8px",
    border: "1px solid var(--border-default)",
    display: "flex",
    flexDirection: "column" as const,
    overflow: "hidden",
    boxShadow: "0 8px 32px rgba(0, 0, 0, 0.5)",
    animation: "skills-modal-in 0.15s ease-out",
  } as React.CSSProperties,
  header: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "8px 16px",
    borderBottom: "1px solid var(--border-default)",
    backgroundColor: "var(--bg-panel)",
    flexShrink: 0,
  } as React.CSSProperties,
  closeBtn: {
    background: "none",
    border: "none",
    color: "var(--text-secondary)",
    fontSize: "18px",
    cursor: "pointer",
    padding: "4px 8px",
    lineHeight: 1,
  } as React.CSSProperties,
  body: {
    padding: "12px 16px",
    overflowY: "auto" as const,
    flex: 1,
  } as React.CSSProperties,
  fetchRow: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    marginBottom: "12px",
  } as React.CSSProperties,
  input: {
    flex: 1,
    background: "var(--bg-input)",
    border: "1px solid var(--border-default)",
    color: "var(--text-primary)",
    fontSize: "var(--font-size-sm)",
    padding: "6px 10px",
    borderRadius: "4px",
    outline: "none",
    fontFamily: "var(--font-family)",
  } as React.CSSProperties,
  actionBtn: {
    background: "transparent",
    border: "1px solid var(--border-medium)",
    color: "var(--text-primary)",
    fontSize: "var(--font-size-sm)",
    padding: "6px 14px",
    borderRadius: "4px",
    cursor: "pointer",
    whiteSpace: "nowrap" as const,
  } as React.CSSProperties,
  accentBtn: {
    background: "var(--accent)",
    border: "none",
    color: "var(--text-on-accent)",
    fontSize: "var(--font-size-sm)",
    padding: "6px 14px",
    borderRadius: "4px",
    cursor: "pointer",
    fontWeight: 600,
    whiteSpace: "nowrap" as const,
  } as React.CSSProperties,
  smallBtn: {
    background: "transparent",
    border: "1px solid var(--border-medium)",
    color: "var(--text-primary)",
    fontSize: "11px",
    padding: "3px 10px",
    borderRadius: "3px",
    cursor: "pointer",
    whiteSpace: "nowrap" as const,
  } as React.CSSProperties,
  removeBtn: {
    background: "none",
    border: "1px solid var(--border-medium)",
    color: "var(--text-secondary)",
    fontSize: "11px",
    padding: "2px 8px",
    borderRadius: "3px",
    cursor: "pointer",
    marginLeft: "8px",
    transition: "color 0.15s, border-color 0.15s",
  } as React.CSSProperties,
  section: {
    marginBottom: "16px",
  } as React.CSSProperties,
  sectionTitle: {
    fontSize: "11px",
    fontWeight: 600,
    textTransform: "uppercase" as const,
    color: "var(--text-secondary)",
    letterSpacing: "0.5px",
    marginBottom: "6px",
    paddingBottom: "4px",
    borderBottom: "1px solid var(--border-subtle)",
  } as React.CSSProperties,
  itemRow: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "5px 0",
    fontSize: "var(--font-size-sm)",
  } as React.CSSProperties,
  dropdownItem: {
    padding: "8px 14px",
    fontSize: "var(--font-size-sm)",
    cursor: "pointer",
    color: "var(--text-primary)",
  } as React.CSSProperties,
};

export const confirmStyles = {
  backdrop: {
    position: "fixed" as const,
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0,0,0,0.4)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 1100,
  } as React.CSSProperties,
  modal: {
    background: "var(--bg-primary)",
    border: "1px solid var(--border-default)",
    borderRadius: "8px",
    padding: "20px 24px",
    maxWidth: "420px",
    width: "100%",
    boxShadow: "0 8px 32px rgba(0,0,0,0.5)",
  } as React.CSSProperties,
};
