import type React from "react";
import { modalStyles } from "../../styles/modal";

export const styles = {
  ...modalStyles,
  fetchRow: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    marginBottom: "12px",
  } as React.CSSProperties,
  input: {
    flex: 1,
    background: "var(--bg-input)",
    border: "1px solid var(--border-default)",
    color: "var(--text-primary)",
    fontSize: "var(--font-size-sm)",
    padding: "6px 10px",
    borderRadius: "4px",
    outline: "none",
    fontFamily: "var(--font-family)",
  } as React.CSSProperties,
  actionBtn: {
    background: "transparent",
    border: "1px solid var(--border-medium)",
    color: "var(--text-primary)",
    fontSize: "var(--font-size-sm)",
    padding: "6px 14px",
    borderRadius: "4px",
    cursor: "pointer",
    whiteSpace: "nowrap" as const,
  } as React.CSSProperties,
  accentBtn: {
    background: "var(--accent)",
    border: "none",
    color: "var(--text-on-accent)",
    fontSize: "var(--font-size-sm)",
    padding: "6px 14px",
    borderRadius: "4px",
    cursor: "pointer",
    fontWeight: 600,
    whiteSpace: "nowrap" as const,
  } as React.CSSProperties,
  smallBtn: {
    background: "transparent",
    border: "1px solid var(--border-medium)",
    color: "var(--text-primary)",
    fontSize: "11px",
    padding: "3px 10px",
    borderRadius: "3px",
    cursor: "pointer",
    whiteSpace: "nowrap" as const,
  } as React.CSSProperties,
  removeBtn: {
    background: "none",
    border: "1px solid var(--border-medium)",
    color: "var(--text-secondary)",
    fontSize: "11px",
    padding: "2px 8px",
    borderRadius: "3px",
    cursor: "pointer",
    marginLeft: "8px",
    transition: "color 0.15s, border-color 0.15s",
  } as React.CSSProperties,
  section: {
    marginBottom: "16px",
  } as React.CSSProperties,
  sectionTitle: {
    fontSize: "11px",
    fontWeight: 600,
    textTransform: "uppercase" as const,
    color: "var(--text-secondary)",
    letterSpacing: "0.5px",
    marginBottom: "6px",
    paddingBottom: "4px",
    borderBottom: "1px solid var(--border-subtle)",
  } as React.CSSProperties,
  itemRow: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "5px 0",
    fontSize: "var(--font-size-sm)",
  } as React.CSSProperties,
  dropdownItem: {
    padding: "8px 14px",
    fontSize: "var(--font-size-sm)",
    cursor: "pointer",
    color: "var(--text-primary)",
  } as React.CSSProperties,
};

export const confirmStyles = {
  backdrop: {
    position: "fixed" as const,
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0,0,0,0.4)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 1100,
  } as React.CSSProperties,
  modal: {
    background: "var(--bg-primary)",
    border: "1px solid var(--border-default)",
    borderRadius: "8px",
    padding: "20px 24px",
    maxWidth: "420px",
    width: "100%",
    boxShadow: "0 8px 32px rgba(0,0,0,0.5)",
  } as React.CSSProperties,
};
